// Fill out your copyright notice in the Description page of Project Settings.


#include "Controller/CSPlayerController.h"
#include "Blueprint/UserWidget.h"
#include "GameFramework/GameStateBase.h"
#include "GameModes/CSLobbyGameMode.h"
#include "GameModes/CSMainMenuGameMode.h"
#include "PlayerStates/CSPlayerState.h"
#include "GameStates/CSLobbyGameState.h"
#include "GameInstance/CSGameInstance.h"
#include "GameStates/CSGameStateBase.h"
#include "UI/CSUIBaseWidget.h"
#include "UI/CSMainMenu.h"
#include "UI/CSLobbyBaseWidget.h"
#include "UI/CSVersusLobbyWidget.h"
#include "UI/CSCoopLobbyWidget.h"
#include "UI/CSInGameHUD.h"
#include "Kismet/GameplayStatics.h"

ACSPlayerController::ACSPlayerController() : CurrentActiveUI(nullptr), bIsHostPlayer(false) {}


void ACSPlayerController::BeginPlay()
{
    Super::BeginPlay();

    if (IsLocalController())
    {
        InitializeCurrentUI();
    }
}

void ACSPlayerController::ClientRestart_Implementation(APawn* NewPawn)
{
    Super::ClientRestart_Implementation(NewPawn);

    UE_LOG(LogTemp, Warning, TEXT("ACSPlayerController::ClientRestart --- Called for Controller: %s"), *GetName());

    if (!IsLocalPlayerController()) {
        UE_LOG(LogTemp, Log, TEXT("ClientRestart: Not Local Player Controller. Skipping UI/Input setup."));
        return;
    }

    UWorld* World = GetWorld();
    UCSGameInstance* GI = GetGameInstance<UCSGameInstance>();
    if (!GI || !World) { UE_LOG(LogTemp, Error, TEXT("ClientRestart: GI or World is NULL!")); return; }

    FName CurrentLevelName = FName(*World->GetName());
    UE_LOG(LogTemp, Log, TEXT("ClientRestart: Level=%s"), *CurrentLevelName.ToString());

    // Î©îÏù∏ Î©îÎâ¥ÎÇò Î°úÎπÑ Î†àÎ≤®ÏóêÏÑúÎäî Ïã§Ìñâ Ïïà Ìï®
    if (CurrentLevelName == FName("MainMenuLevel") || CurrentLevelName == FName("LobbyLevel")) { return; }

    UE_LOG(LogTemp, Warning, TEXT("ClientRestart: In Gameplay Level. Setting up HUD and Game Input Mode..."));

    // Í∏∞Ï°¥ UI Ï†úÍ±∞
    if (CurrentActiveUI) { CurrentActiveUI->RemoveFromParent(); CurrentActiveUI = nullptr; }

    // Î†àÎ≤®Ïóê ÎßûÎäî HUD ÌÅ¥ÎûòÏä§ Í≤∞Ï†ï
    TSubclassOf<UCSUIBaseWidget> UIClassToCreate = nullptr;
    // ... (Î†àÎ≤® Ïù¥Î¶ÑÏúºÎ°ú HUD ÌÅ¥ÎûòÏä§ Í≤∞Ï†ï Î°úÏßÅ - Ïù¥Ï†ÑÍ≥º ÎèôÏùº) ...
    if (CurrentLevelName == FName("SingleModeLevel")) { UIClassToCreate = StageHUDClass; }
    else if (CurrentLevelName == FName("SingleModeBossLevel")) { UIClassToCreate = BossHUDClass; }
    else if (CurrentLevelName == FName("VersusModeLevel")) { UIClassToCreate = VersusHUDClass; }
    else if (CurrentLevelName == FName("CoopModeLevel")) { UIClassToCreate = CoopHUDClass; }
    else { UE_LOG(LogTemp, Warning, TEXT("ClientRestart: Unknown Gameplay Level %s"), *CurrentLevelName.ToString()); }

    // HUD ÏÉùÏÑ± Î∞è ÌëúÏãú
    if (UIClassToCreate) {
        CurrentActiveUI = CreateWidget<UCSUIBaseWidget>(this, UIClassToCreate);
        if (CurrentActiveUI) {
            CurrentActiveUI->AddToViewport();
            UE_LOG(LogTemp, Log, TEXT("ClientRestart: Initialized Gameplay UI: %s"), *UIClassToCreate->GetName());
        }
        else { UE_LOG(LogTemp, Error, TEXT("ClientRestart: CreateWidget FAILED!")); }
    }
    else { UE_LOG(LogTemp, Warning, TEXT("ClientRestart: No HUD Class determined!")); }

    // ÏûÖÎ†• Î™®Îìú ÏÑ§Ï†ï (GameOnly)
    FInputModeGameOnly InputModeData;
    SetInputMode(InputModeData);
    bShowMouseCursor = false;
    UE_LOG(LogTemp, Warning, TEXT("ClientRestart: >>> Input Mode SET TO GAME ONLY <<<"));

    // Î∑∞Ìè¨Ìä∏ Ìè¨Ïª§Ïä§ ÏÑ§Ï†ï
    FSlateApplication::Get().SetUserFocusToGameViewport(0);
    UE_LOG(LogTemp, Log, TEXT("ClientRestart: >>> Set Focus to Game Viewport <<<"));
}

// InitializeCurrentUI Ìï®Ïàò Îã®ÏàúÌôî: Î©îÏù∏ Î©îÎâ¥Îßå Ï≤òÎ¶¨
void ACSPlayerController::InitializeCurrentUI()
{
    UWorld* World = GetWorld();
    UCSGameInstance* GI = GetGameInstance<UCSGameInstance>();
    if (!GI || !World) return;

    FName CurrentLevelName = FName(*World->GetName());
    UE_LOG(LogTemp, Log, TEXT("InitializeCurrentUI: Checking Level=%s"), *CurrentLevelName.ToString());

    // --- Î°úÎπÑ Î†àÎ≤® ÏòàÏô∏ Ï≤òÎ¶¨ Ïú†ÏßÄ ---
    if (CurrentLevelName == FName("LobbyLevel")) {
        UE_LOG(LogTemp, Log, TEXT("InitializeCurrentUI: In LobbyLevel, skipping UI creation/removal logic."));
        // Î°úÎπÑ ÏßÑÏûÖ Ïãú ÏûÖÎ†• Î™®ÎìúÎäî Client_ShowLobbyUI ÏóêÏÑú Ï≤òÎ¶¨
        return;
    }
    // --- ÏòàÏô∏ Ï≤òÎ¶¨ ÎÅù ---

    // Îã§Î•∏ Î†àÎ≤®ÏóêÏÑú ÌòπÏãú ÎÇ®ÏïÑÏûàÏùÑ Ïàò ÏûàÎäî UI Ï†úÍ±∞
    if (CurrentActiveUI) {
        CurrentActiveUI->RemoveFromParent();
        CurrentActiveUI = nullptr;
    }

    // Î©îÏù∏ Î©îÎâ¥ Î†àÎ≤®Ïùº Í≤ΩÏö∞ÏóêÎßå Î©îÏù∏ Î©îÎâ¥ UI Î°úÎìú
    if (CurrentLevelName == FName("MainMenuLevel")) {
        TSubclassOf<UCSUIBaseWidget> UIClassToCreate = MainMenuWidgetClass;
        if (UIClassToCreate) {
            CurrentActiveUI = CreateWidget<UCSUIBaseWidget>(this, UIClassToCreate);
            if (CurrentActiveUI) {
                CurrentActiveUI->AddToViewport();
                UE_LOG(LogTemp, Log, TEXT("InitializeCurrentUI: Initialized UI: %s"), *UIClassToCreate->GetName());
                // Î©îÏù∏ Î©îÎâ¥ ÏûÖÎ†• Î™®Îìú ÏÑ§Ï†ï
                FInputModeUIOnly InputModeData;
                InputModeData.SetWidgetToFocus(CurrentActiveUI->TakeWidget()); // Î©îÏù∏ Î©îÎâ¥Ïóê Ìè¨Ïª§Ïä§
                SetInputMode(InputModeData);
                bShowMouseCursor = true;
                UE_LOG(LogTemp, Log, TEXT("InitializeCurrentUI: Set Input Mode to UIOnly for MainMenu."));
            }
            else { UE_LOG(LogTemp, Error, TEXT("InitializeCurrentUI: Failed to create MainMenuWidget!")); }
        }
        else { UE_LOG(LogTemp, Warning, TEXT("InitializeCurrentUI: MainMenuWidgetClass is not set!")); }
    }
    else {
        UE_LOG(LogTemp, Log, TEXT("InitializeCurrentUI: Not MainMenuLevel, UI will be handled by OnPossess or Client_ShowLobbyUI."));
    }
}

void ACSPlayerController::Client_ShowLobbyUI_Implementation()
{
    if (!IsLocalController()) return;
    if (CurrentActiveUI) { CurrentActiveUI->RemoveFromParent(); CurrentActiveUI = nullptr; }

    UCSGameInstance* GI = GetGameInstance<UCSGameInstance>();

    EMatchType CurrentMatchType = GI->GetMatchType();
    TSubclassOf<UCSLobbyBaseWidget> LobbyClassToCreate = nullptr;

    if (CurrentMatchType == EMatchType::EMT_Versus) {
        LobbyClassToCreate = VersusLobbyWidgetClass;
    }
    else if (CurrentMatchType == EMatchType::EMT_Coop) {
        LobbyClassToCreate = CoopLobbyWidgetClass;
    }

    if (LobbyClassToCreate) {
        UCSLobbyBaseWidget* LobbyWidget = CreateWidget<UCSLobbyBaseWidget>(this, LobbyClassToCreate);
        if (LobbyWidget) {
            CurrentActiveUI = LobbyWidget;
            CurrentActiveUI->AddToViewport();
            LobbyWidget->InitializeLobby(CurrentMatchType); // Ï¥àÍ∏∞Ìôî Ìï®Ïàò Ìò∏Ï∂ú
            // UI ÏûÖÎ†• Î™®Îìú ÏÑ§Ï†ï
            FInputModeUIOnly InputModeData;
            InputModeData.SetWidgetToFocus(CurrentActiveUI->TakeWidget());
            SetInputMode(InputModeData);
            bShowMouseCursor = true;
        }
    }
}

void ACSPlayerController::Client_ShowNoSessionPopup_Implementation()
{
    if (IsLocalController()) {
        InitializeCurrentUI();
        UCSMainMenu* MainMenuWidget = Cast<UCSMainMenu>(GetCurrentUI());
        if (MainMenuWidget) {
            MainMenuWidget->ShowNotification(FText::FromString(TEXT("[Ìò∏Ïä§Ìä∏Í∞Ä ÏÑ∏ÏÖòÏùÑ ÏÉùÏÑ±ÌïòÏßÄ ÏïäÏïòÏäµÎãàÎã§.]")));
        }
    }
}

bool ACSPlayerController::Server_RequestTeamChange_Validate() { return true; }
void ACSPlayerController::Server_RequestTeamChange_Implementation()
{
    ACSLobbyGameMode* LobbyGameMode = GetWorld()->GetAuthGameMode<ACSLobbyGameMode>();
    if (LobbyGameMode) { LobbyGameMode->ChangeTeam(this); }
}

bool ACSPlayerController::Server_SelectCharacter_Validate(EJobTypes SelectedJob) { return true; }
void ACSPlayerController::Server_SelectCharacter_Implementation(EJobTypes SelectedJob)
{
    ACSLobbyGameMode* LobbyGameMode = GetWorld()->GetAuthGameMode<ACSLobbyGameMode>();
    if (LobbyGameMode) {
        // LobbyGameModeÏùò SetPlayerSelection Ìï®Ïàò ÏãúÍ∑∏ÎãàÏ≤òÎèÑ EJobTypes Î°ú Î≥ÄÍ≤Ω ÌïÑÏöî
        // ÌôïÏù∏ ÌõÑ Ìò∏Ï∂ú ÎòêÎäî Ï£ºÏÑù Ï≤òÎ¶¨
        LobbyGameMode->SetSelectedPlayerJob(this, SelectedJob);
    }
}

bool ACSPlayerController::Server_RequestReady_Validate(bool bReady) { return true; }
void ACSPlayerController::Server_RequestReady_Implementation(bool bReady)
{
    ACSPlayerState* PS = GetPlayerState<ACSPlayerState>();
    if (PS) { PS->SetIsReady(bReady); }
    else { UE_LOG(LogTemp, Warning, TEXT("Server_RequestReady: PlayerState not found.")); }
}

bool ACSPlayerController::Server_RequestReturnToMainMenu_Validate() { return true; }
void ACSPlayerController::Server_RequestReturnToMainMenu_Implementation()
{
    // TODO: Î©îÏù∏ Î©îÎâ¥ Î†àÎ≤®Î°ú Ïù¥Îèô
    UWorld* World = GetWorld();
    if (World) {
        UE_LOG(LogTemp, Log, TEXT("Server: Returning to Main Menu..."));
        // UGameplayStatics::OpenLevel(World, FName("MainMenuLevel")); // ÌÅ¥ÎùºÏù¥Ïñ∏Ìä∏ÏóêÍ≤åÎäî Ï†ÅÏö© Ïïà Îê®
        // Î™®Îì† ÌÅ¥ÎùºÏù¥Ïñ∏Ìä∏ÏóêÍ≤å Ïù¥Îèô Î™ÖÎ†π ÌïÑÏöî
        // GetWorld()->ServerTravel(TEXT("/Game/Maps/MainMenuLevel?listen")); // Î¶¨Ïä® ÏÑúÎ≤Ñ Ìò∏Ïä§Ìä∏Îßå Ïù¥Îèô
        // TODO: Í∞Å ÌÅ¥ÎùºÏù¥Ïñ∏Ìä∏Í∞Ä Ïä§Ïä§Î°ú MainMenuLevel Î°ú Ïù¥ÎèôÌïòÎèÑÎ°ù Ï≤òÎ¶¨ (Ïòà: GameModeÏóêÏÑú RPC Ìò∏Ï∂ú)
        AGameModeBase* GM = World->GetAuthGameMode();
        // if (GM) GM->RequestClientsReturnToMainMenu(); // GameModeÏóê Ìï®Ïàò Ï∂îÍ∞Ä ÌïÑÏöî
    }
}

void ACSPlayerController::Client_OnSuddenDeath_Implementation()
{
    if (IsLocalController() && CurrentActiveUI) {
        // CurrentActiveUI->TriggerSuddenDeathUI(); // ÏúÑÏ†Ø Ìï®Ïàò Ìò∏Ï∂ú
    }
}

void ACSPlayerController::RequestEnterMultiplayerMode(EMatchType NewMatchType)
{
    if (UCSGameInstance* GameInstance = GetGameInstance<UCSGameInstance>())
    {
        UE_LOG(LogTemp, Warning, TEXT("üü© RequestEnterMultiplayerMode | Player: %s | NetMode: %d | IsHost: %d"),
            *GetName(), (int32)GetNetMode(), bIsHostPlayer);

        if (bIsHostPlayer) // Listen Server
        {
            GameInstance->SetMatchType(NewMatchType);
            GameInstance->HostSession(NewMatchType);
        }
        else // Client
        {
            GameInstance->SetMatchType(NewMatchType);
            GameInstance->FindSessions();
        }
    }
}

void ACSPlayerController::HealthUpdate(float Health, float MaxHealth)
{
    if (IsLocalController() && CurrentActiveUI) {
        if (UCSInGameHUD* HUD = Cast<UCSInGameHUD>(CurrentActiveUI)) {
            HUD->UpdateHealth(Health, MaxHealth);
        }
    }
}

// Îß§Ïπò Îã®Í≥Ñ Î≥ÄÍ≤Ω
void ACSPlayerController::OnMatchPhaseChanged(EMatchPhase MatchPhase)
{
    if (IsLocalController() && CurrentActiveUI) {
        // CurrentActiveUI->HandleMatchPhaseChanged(MatchPhase); // ÏúÑÏ†Ø Ìï®Ïàò Ìò∏Ï∂ú
    }
}